# fly.toml app configuration file generated for fantasy-files-v2 on 2024-06-04T14:46:41-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fantasy-files'
primary_region = 'iad'
kill_signal = "SIGTERM"
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000
[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
[checks]
  [checks.name_of_your_http_check]
    grace_period = "30s"
    interval = "15s"
    method = "get"
    path = "/path/to/status"
    port = 5500
    timeout = "10s"
    type = "http"
    [checks.name_of_your_http_check.headers]
      Content-Type = "application/json"
      Authorization = "super-secret"

  [checks.name_of_your_tcp_check]
    grace_period = "30s"
    interval = "15s"
    port = 1234
    timeout = "10s"
    type = "tcp"
